name = "larcform1-experiments"
authors = ["Jeffrey Yoder <jeffreyyoder@unr.edu"]

[deps]
AtmosphericProfilesLibrary = "86bc3604-9858-485a-bdbe-831ec50de11d"
ClimaAtmos = "b2c96348-7fb7-4fe0-8da9-78d88439e717"
ClimaCoupler = "4ade58fe-a8da-486c-bd89-46df092ec0c7"
